use std::fs;
use std::hash::{Hash, Hasher};
use std::path::{Path, PathBuf};

use crate::config::FindeskConfig;
use crate::finsafe::profiles::{self, ProfileContext};

const FINSAFE_SECRET_ENV_KEYS: &[&str] = &[
    "OPENAI_API_KEY",
    "ANTHROPIC_API_KEY",
    "API_KEY",
    "CODEX_API_KEY",
    "AWS_ACCESS_KEY_ID",
    "AWS_SECRET_ACCESS_KEY",
    "AWS_SESSION_TOKEN",
    "GOOGLE_API_KEY",
    "GEMINI_API_KEY",
    "FINCLAW_LLM_API_KEY",
    "DEEPSEEK_API_KEY",
    "OPENROUTER_API_KEY",
    "DASHSCOPE_API_KEY",
    "MOONSHOT_API_KEY",
    "MINIMAX_API_KEY",
    "ZHIPUAI_API_KEY",
];

const FINSAFE_PASSTHROUGH_ENV_KEYS: &[&str] = &[
    "AWS_REGION",
    "AWS_PROFILE",
    "BUN_INSTALL_CACHE_DIR",
    "BUN_TMPDIR",
    "TMP",
    "TEMP",
    "TMPDIR",
    "PATH",
    "HOME",
    "USER",
    "USERPROFILE",
    "SSL_CERT_FILE",
    "SSL_CERT_DIR",
];

fn yaml_quote_path(path: &Path) -> String {
    let value = path.to_string_lossy();
    if value
        .chars()
        .all(|c| c.is_ascii_alphanumeric() || matches!(c, '_' | '.' | '/' | '-'))
    {
        value.into_owned()
    } else {
        serde_json::to_string(&value).unwrap_or_else(|_| format!("\"{value}\""))
    }
}

pub fn build_runtime_policy_yaml(ctx: &ProfileContext, config: &FindeskConfig) -> String {
    let profile_id = profiles::resolve_profile_id(&ctx.backend);
    let read_only = profiles::resolve_read_only_paths(ctx, config);
    let mut read_write = profiles::resolve_read_write_paths(ctx, config);
    read_write.extend(profiles::macos_temp_paths());

    let program_mode = if profiles::uses_interactive_program_mode(ctx) {
        "interactive"
    } else {
        "short-lived"
    };
    let timeout_ms = if program_mode == "interactive" {
        3_600_000
    } else {
        120_000
    };

    let read_only_yaml = read_only
        .iter()
        .map(|p| format!("    - {}", yaml_quote_path(p)))
        .collect::<Vec<_>>()
        .join("\n");
    let read_write_yaml = read_write
        .iter()
        .map(|p| format!("    - {}", yaml_quote_path(p)))
        .collect::<Vec<_>>()
        .join("\n");

    // Build line-by-line: Rust `\` string continuations strip leading whitespace on
    // the next line, which breaks YAML nesting (e.g. degrade.allow_fallback).
    let mut lines = vec![
        format!(
            "# Generated by aionui-findesk (profile: {profile_id}, backend: {}).",
            ctx.backend
        ),
        "schema_version: 1".to_string(),
        "kind: local-wrapper".to_string(),
        format!("program_mode: {program_mode}"),
        "degrade:".to_string(),
        "  allow_fallback: true".to_string(),
        "audit:".to_string(),
        "  require_policy_digest: true".to_string(),
        "  require_resolved_posture: true".to_string(),
        "stdio:".to_string(),
        "  mode: inherit".to_string(),
        "network: host".to_string(),
        "resources:".to_string(),
        "  memory_max: \"2G\"".to_string(),
        "  pids_max: \"512\"".to_string(),
        "  cpu_max: \"100000 100000\"".to_string(),
        format!("  timeout_ms: {timeout_ms}"),
        "filesystem:".to_string(),
        "  skip_default_deny_read: true".to_string(),
        "  read_only_paths:".to_string(),
    ];
    if !read_only_yaml.is_empty() {
        lines.push(read_only_yaml);
    }
    lines.push("  read_write_paths:".to_string());
    if !read_write_yaml.is_empty() {
        lines.push(read_write_yaml);
    }
    lines.join("\n") + "\n"
}

fn policy_cache_dir(config: &FindeskConfig) -> PathBuf {
    config
        .cache_dir
        .clone()
        .or_else(|| config.work_dir.clone())
        .unwrap_or_else(std::env::temp_dir)
        .join("findesk")
        .join("finsafe-policies")
}

pub fn resolve_runtime_policy_path(ctx: &ProfileContext, config: &FindeskConfig) -> std::io::Result<PathBuf> {
    let yaml = build_runtime_policy_yaml(ctx, config);
    let mut hasher = std::collections::hash_map::DefaultHasher::new();
    yaml.hash(&mut hasher);
    let digest = hasher.finish();

    let dir = policy_cache_dir(config);
    fs::create_dir_all(&dir)?;
    let path = dir.join(format!(
        "{}-{:016x}.yaml",
        profiles::resolve_profile_id(&ctx.backend),
        digest
    ));
    // Always refresh so policy fixes apply even when the content hash is unchanged.
    fs::write(&path, yaml)?;
    Ok(path)
}

pub fn pick_env_for_sandbox(child_env: &std::collections::HashMap<String, String>) -> Vec<String> {
    pick_env_keys_for_sandbox(child_env, FINSAFE_PASSTHROUGH_ENV_KEYS)
}

/// Non-secret env vars may be passed via `/usr/bin/env` argv; secrets stay in `child_env` only.
pub fn pick_non_secret_env_for_sandbox(child_env: &std::collections::HashMap<String, String>) -> Vec<String> {
    pick_env_keys_for_sandbox(child_env, FINSAFE_PASSTHROUGH_ENV_KEYS)
}

fn pick_env_keys_for_sandbox(child_env: &std::collections::HashMap<String, String>, keys: &[&str]) -> Vec<String> {
    let mut pairs = Vec::new();
    for key in keys {
        if FINSAFE_SECRET_ENV_KEYS.contains(key) {
            continue;
        }
        if let Some(value) = child_env.get(*key)
            && !value.is_empty()
        {
            pairs.push(format!("{key}={value}"));
        }
    }
    pairs
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::path::PathBuf;

    #[test]
    fn finclaw_policy_includes_skip_default_deny_read() {
        let ctx = ProfileContext {
            backend: "finclaw".into(),
            executable: PathBuf::from("/usr/local/bin/finclaw"),
            cwd: Some(PathBuf::from("/tmp/workspace")),
            home_dir: PathBuf::from("/home/user"),
            wrapper_mode: aionui_runtime::SpawnWrapperMode::InteractiveSelfConfine,
        };
        let config = FindeskConfig {
            finsafe_bin: None,
            finsafe_policies_dir: None,
            finclaw_bin: None,
            cache_dir: Some(PathBuf::from("/cache")),
            work_dir: Some(PathBuf::from("/work")),
            log_dir: None,
        };
        let yaml = build_runtime_policy_yaml(&ctx, &config);
        assert!(yaml.contains("skip_default_deny_read: true"));
        assert!(yaml.contains("program_mode: interactive"));
        assert!(yaml.contains(".finclaw"));
        assert!(
            yaml.contains("degrade:\n  allow_fallback: true"),
            "degrade.allow_fallback must be nested YAML; got:\n{yaml}"
        );
    }

    #[test]
    fn hermes_interactive_sdk_policy_uses_one_hour_timeout() {
        let ctx = ProfileContext {
            backend: "hermes".into(),
            executable: PathBuf::from("/Users/tester/.local/bin/hermes"),
            cwd: Some(PathBuf::from("/tmp/workspace")),
            home_dir: PathBuf::from("/Users/tester"),
            wrapper_mode: aionui_runtime::SpawnWrapperMode::InteractiveSelfConfine,
        };
        let config = FindeskConfig {
            finsafe_bin: None,
            finsafe_policies_dir: None,
            finclaw_bin: None,
            cache_dir: Some(PathBuf::from("/cache")),
            work_dir: Some(PathBuf::from("/work")),
            log_dir: None,
        };
        let yaml = build_runtime_policy_yaml(&ctx, &config);
        assert!(yaml.contains("program_mode: interactive"));
        assert!(yaml.contains("timeout_ms: 3600000"));
    }

    #[test]
    fn non_secret_env_pairs_exclude_api_keys() {
        let mut env = std::collections::HashMap::new();
        env.insert("OPENAI_API_KEY".into(), "sk-secret".into());
        env.insert("PATH".into(), "/usr/bin".into());
        let pairs = pick_non_secret_env_for_sandbox(&env);
        assert_eq!(pairs, vec!["PATH=/usr/bin"]);
    }
}
