use std::fs;
use std::hash::{Hash, Hasher};
use std::path::{Path, PathBuf};

use crate::config::FindeskConfig;
use crate::finsafe::profiles::{self, ProfileContext};

const FINSAFE_PASSTHROUGH_ENV_KEYS: &[&str] = &[
    "OPENAI_API_KEY",
    "ANTHROPIC_API_KEY",
    "API_KEY",
    "CODEX_API_KEY",
    "AWS_ACCESS_KEY_ID",
    "AWS_SECRET_ACCESS_KEY",
    "AWS_SESSION_TOKEN",
    "AWS_REGION",
    "AWS_PROFILE",
    "GOOGLE_API_KEY",
    "GEMINI_API_KEY",
    "BUN_INSTALL_CACHE_DIR",
    "BUN_TMPDIR",
    "TMP",
    "TEMP",
    "TMPDIR",
    "PATH",
    "HOME",
    "USER",
    "USERPROFILE",
    "SSL_CERT_FILE",
    "SSL_CERT_DIR",
];

fn yaml_quote_path(path: &Path) -> String {
    let value = path.to_string_lossy();
    if value
        .chars()
        .all(|c| c.is_ascii_alphanumeric() || matches!(c, '_' | '.' | '/' | '-'))
    {
        value.into_owned()
    } else {
        serde_json::to_string(&value).unwrap_or_else(|_| format!("\"{value}\""))
    }
}

pub fn build_runtime_policy_yaml(ctx: &ProfileContext, config: &FindeskConfig) -> String {
    let profile_id = profiles::resolve_profile_id(&ctx.backend);
    let read_only = profiles::resolve_read_only_paths(ctx, config);
    let mut read_write = profiles::resolve_read_write_paths(ctx, config);
    read_write.extend(profiles::macos_temp_paths());

    let program_mode = if ctx.backend == "finclaw" {
        "interactive"
    } else {
        "short-lived"
    };
    let timeout_ms = if program_mode == "interactive" {
        3_600_000
    } else {
        120_000
    };

    let read_only_yaml = read_only
        .iter()
        .map(|p| format!("    - {}", yaml_quote_path(p)))
        .collect::<Vec<_>>()
        .join("\n");
    let read_write_yaml = read_write
        .iter()
        .map(|p| format!("    - {}", yaml_quote_path(p)))
        .collect::<Vec<_>>()
        .join("\n");

    format!(
        "# Generated by aionui-findesk (profile: {profile_id}, backend: {}).\n\
schema_version: 1\n\
kind: local-wrapper\n\
program_mode: {program_mode}\n\
degrade:\n\
  allow_fallback: true\n\
audit:\n\
  require_policy_digest: true\n\
  require_resolved_posture: true\n\
stdio:\n\
  mode: inherit\n\
network: host\n\
resources:\n\
  memory_max: \"2G\"\n\
  pids_max: \"512\"\n\
  cpu_max: \"100000 100000\"\n\
  timeout_ms: {timeout_ms}\n\
filesystem:\n\
  skip_default_deny_read: true\n\
  read_only_paths:\n\
{read_only_yaml}\n\
  read_write_paths:\n\
{read_write_yaml}\n",
        ctx.backend
    )
}

fn policy_cache_dir(config: &FindeskConfig) -> PathBuf {
    config
        .cache_dir
        .clone()
        .or_else(|| config.work_dir.clone())
        .unwrap_or_else(std::env::temp_dir)
        .join("findesk")
        .join("finsafe-policies")
}

pub fn resolve_runtime_policy_path(ctx: &ProfileContext, config: &FindeskConfig) -> std::io::Result<PathBuf> {
    let yaml = build_runtime_policy_yaml(ctx, config);
    let mut hasher = std::collections::hash_map::DefaultHasher::new();
    yaml.hash(&mut hasher);
    let digest = hasher.finish();

    let dir = policy_cache_dir(config);
    fs::create_dir_all(&dir)?;
    let path = dir.join(format!(
        "{}-{:016x}.yaml",
        profiles::resolve_profile_id(&ctx.backend),
        digest
    ));
    if !path.exists() {
        fs::write(&path, yaml)?;
    }
    Ok(path)
}

pub fn pick_env_for_sandbox(child_env: &std::collections::HashMap<String, String>) -> Vec<String> {
    let mut pairs = Vec::new();
    for key in FINSAFE_PASSTHROUGH_ENV_KEYS {
        if let Some(value) = child_env.get(*key)
            && !value.is_empty()
        {
            pairs.push(format!("{key}={value}"));
        }
    }
    pairs
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::path::PathBuf;

    #[test]
    fn finclaw_policy_includes_skip_default_deny_read() {
        let ctx = ProfileContext {
            backend: "finclaw".into(),
            executable: PathBuf::from("/usr/local/bin/finclaw"),
            cwd: Some(PathBuf::from("/tmp/workspace")),
            home_dir: PathBuf::from("/home/user"),
        };
        let config = FindeskConfig {
            finsafe_bin: None,
            finsafe_policies_dir: None,
            finclaw_bin: None,
            cache_dir: Some(PathBuf::from("/cache")),
            work_dir: Some(PathBuf::from("/work")),
            log_dir: None,
        };
        let yaml = build_runtime_policy_yaml(&ctx, &config);
        assert!(yaml.contains("skip_default_deny_read: true"));
        assert!(yaml.contains("program_mode: interactive"));
        assert!(yaml.contains(".finclaw"));
    }
}
